---
title: "coded_distributions"
author: "Lin Yang, Yida Wang"
date: "2022-05-04"
output: pdf_document
---

```{r, setup}
source("shared_code/setup.R")
source("shared_code/data_cleaning.R")
```

## Little Sigma^2

```{r}
#function calculating beta in inverse gamma distribution
n_hur <- 700
beta_gamma <- function(dat, B, nhur) {
  res = NULL
  for (j in 1:nhur) {
    subdat = dat %>% filter(i == j)
    y = subdat[, 2]
    x = cbind(rep(1, nrow(subdat)), subdat[, 3:6]) %>% as.matrix()
    beta = 0.5*(sum((y - x %*% t(B[j, ]))^2))
    res = rbind(res, beta)
  }
  return(sum(res))
}

#test function
B <- data.frame(matrix(1, nrow = 700, ncol = 5))
#beta_gamma <- beta_gamma(dt, B)

sigmasq <- function(dat, B) {
  alpha = nrow(dat)/2
  beta = beta_gamma(dat, B)
  sigmasq = rinvgamma(1, alpha = alpha, beta = beta) 
  return(sigmasq)
}

set.seed(2022)
sigmasq(dt, B)
```

## Big B

```{r}
#function calculating beta in MVN
n_hur <- 700
beta_i <- function(dat, siginv, sigmasqinv, mu, n_hur) {
  res = rep(NA,5)
  newdat <- dat
  
  for (j in 1:n_hur) {
    j = 1
    subdat = newdat %>% dplyr::filter(i == j)
    y = subdat[, 2]
    x = cbind(rep(1, nrow(subdat)), subdat[, 3:6]) %>% as.matrix()
    I = diag(x = 1, nrow(subdat), nrow(subdat))
    Vinv = solve(siginv + sigmasqinv*(t(x) %*% I %*% x))
    M = sigmasqinv*(t(y)%*% I %*%x) + t(mu) %*% siginv
    betai = mvrnorm(1, Vinv %*% t(M), Vinv)
    res = rbind(res, betai)
    j = j+1
  }
  return(res)
}

siginv <- matrix(1, nrow = 5, ncol = 5)
sigmasqinv = 0.2
mu <- c(1,1,1,1,1)
aa <- beta_i(dt, siginv, sigmasqinv, mu) %>% na.omit()
```





