---
title: "EDA"
author: "Yida Wang"
date: "5/5/2022"
output: html_document
---

```{r}
library(ggplot2)
source("shared_code/data_cleaning.R")

ggplot(data=raw, aes(x = longitude, y = latitude)) + 
  stat_summary_2d(data = raw, 
                  aes(x = longitude, 
                      y = latitude, 
                      z = wind_kt), 
                  fun = median, binwidth = c(1, 1), show.legend = TRUE)

library(data.table)
raw <- as.data.table(raw)
summary(dt)
```

```{r}
library(maps)

eda_dat <-
  raw %>%
  group_by(id) %>%
  mutate(
    day = day(time),
    year = season,
    time = hour(time),
    group_id = cur_group_id()
  )

map <- ggplot(data = raw, aes(x = longitude, y = latitude)) + 
  geom_polygon(data = map_data(map = 'world'), aes(x = long, y = lat, group = group))

map +
  stat_summary_2d(data = raw, aes(x = longitude, y = latitude, z = wind_kt), fun = median, binwidth = c(1, 1), show.legend = TRUE, alpha = 0.75) + 
  ggtitle(paste0("Atlantic Windstorm mean knot"))
```

```{r}
map <- ggplot(raw, aes(x = longitude, y = latitude, group = id)) + 
  geom_polygon(data = map_data("world"), 
               aes(x = long, y = lat, group = group), 
               fill = "gray25", colour = "gray10", size = 0.2) + 
  geom_path(data = raw, aes(group = id, colour = wind_kt), size = 0.5) + 
  xlim(-138, -20) + ylim(3, 55) + 
  labs(x = "", y = "", colour = "Wind \n(knots)") + 
  theme(panel.background = element_rect(fill = "gray10", colour = "gray30"),
        axis.text.x = element_blank(), axis.text.y = element_blank(), 
        axis.ticks = element_blank(), panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())

seasonrange <- paste(range(raw[, season]), collapse=" - ")

map + ggtitle(paste("Atlantic named Windstorm Trajectories (", 
                     seasonrange, ")\n")) 
```

```{r}
mapMonth <- map + facet_wrap(~ month) +
  ggtitle(paste("Atlantic named Windstorm Trajectories by Month (", 
                 seasonrange, ")\n")) 
mapMonth
```

