---
title: "Gibbs_sampling"
author: "Jibei Zheng"
date: "2022/5/5"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(extraDistr)
library(MASS)
library(mixAK)
library(progress)
library(foreach)
library(doParallel)
library(doRNG)
library(pracma)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

numCores = detectCores()
registerDoParallel(numCores) 
```


```{r}
source("shared_code/data_cleaning.R")
dt = train

temp = distinct(dt, i) %>% add_rownames("new_i")
dt = dt %>% left_join(temp)
dt = dt %>% dplyr::select(-wkt_old)

```

functions:

```{r}
#function calculating beta in inverse gamma distribution
beta_gamma <- function(dat, B) {
  
  N = nrow(B)
  res = foreach(j = 1:N, .combine = "+", .packages = c("tidyverse")) %dopar% {
    subdat = dat %>% filter(new_i == j)
    y = subdat[, 2]
    x = cbind(rep(1, nrow(subdat)), subdat[, 3:6]) %>% as.matrix()
    beta = 0.5*(sum((y - x %*% t(B[j, ]))^2))
  }
  return(res)
}

sigmasq <- function(dat, B) {
  alpha = nrow(dat)/2
  beta = beta_gamma(dat, B)
  sigmasq = extraDistr::rinvgamma(1, alpha = alpha, beta = beta) 
  return(sigmasq)
}


#function generating B
beta_i <- function(dat, siginv, sigmasqinv, mu) {
  
  newdat <- dat
  N = length(unique(dat$new_i))
  
  res = foreach(j = 1:N, .combine = "rbind", .packages = c("tidyverse", "mixAK", "MASS", "pracma")) %dorng% {
    subdat = newdat %>% dplyr::filter(new_i == j)
    y = subdat[, 2]
    x = cbind(rep(1, nrow(subdat)), subdat[, 3:6]) %>% as.matrix()
    I = diag(x = 1, nrow(subdat), nrow(subdat))
    Vinv = pinv(siginv + sigmasqinv*(t(x) %*% I %*% x))
    M = sigmasqinv*(t(y) %*% I %*% x) + t(mu) %*% siginv
    mvrnorm(1, Vinv %*% t(M), Vinv)
  }
  res = res %>% na.omit()
  
  return(as.data.frame(res))
}

#siginv <- matrix(1, nrow = 5, ncol = 5)
#sigmasqinv = 0.2
#mu <- c(1,1,1,1,1)
#beta_i(dt, siginv, sigmasqinv, mu)

# function generating mu
mufun = function(B, SIGMA) {
  
  N = nrow(B)
  V = N * solve(SIGMA)
  M = solve(SIGMA) %*% colSums(B)
  
  mu = mvrnorm(mu = solve(V) %*% M, Sigma = solve(V))
  
  return(mu)
  
}

#function generating SIGMA
SIGMAfun = function(B, mu) {
  
  B = as.matrix(B)
  N = nrow(B)
  n = 18 + N
  S = diag(0,5)
  for (i in 1:N) {
    S = S + (B[i,] - mu) %*% t(B[i,] - mu)
  }
  S = S + diag(1,5)
  Sinv = solve(S)
  
  SIGMA = rWISHART(1, df=n, S=Sinv)
  
  return(solve(SIGMA))
}

#SIGMAfun(testB, mm)

#Gibbs
gibbsfun = function(y, B, mu, sigmasq, SIGMA, niter=1000, Bfun, mufun, sigmasqfun, SIGMAfun) {
  
  Bvec = list(B)
  muvec = list(mu)
  sigmasqvec = rep(NA, niter)
  sigmasqvec[1] = sigmasq
  SIGMAvec = list(SIGMA)
  
  for (k in 2:niter) {
    pb1$tick()
    Bvec[[k]] = Bfun(y, solve(SIGMAvec[[k - 1]]), 1/sigmasqvec[k - 1], muvec[[k - 1]]) 
    muvec[[k]] = mufun(Bvec[[k]], SIGMAvec[[k - 1]])
    sigmasqvec[k] = sigmasqfun(y, Bvec[[k]])
    SIGMAvec[[k]] = SIGMAfun(Bvec[[k]], muvec[[k]])
  }
  
  return(list(B = Bvec, mu = muvec, sigmasq = sigmasqvec, SIGMA = SIGMAvec))
  
}

```



```{r}
B <- data.frame(matrix(1, nrow = length(unique(dt$new_i)), ncol = 5))

#run 1
iter1 <- 10000
set.seed(20220507)
pb1 <- progress_bar$new(format = "gibbs sampling... [:bar] :percent eta: :eta",
                        total = iter1 - 1)

res = gibbsfun(dt, B, mu = rep(1,5), sigmasq = 1, SIGMA = diag(1,5), niter = iter1, 
         beta_i, mufun, sigmasq, SIGMAfun)

save(res, file = "mcmc1.RData")


#test
testB = res$B[[10000]]
testmu = res$mu[[10000]]
testsigmasq = res$sigmasq[[10000]]
testSIGMA = res$SIGMA[[10000]]

#mean(testB[1:642,1])
#sum(testB[,1] > 0.00001)

#660(643)
```

plots:

```{r}
burn = 2000
chain_length = res[[1]] %>% length() 

#beta
cur_B = data.frame()
for (i in 1:5) {
  for (j in (burn+1):chain_length) {
    cur_B[j-burn,i] = res$B[[j]][32,i]
  }
}
colnames(cur_B) = paste0("beta", 0:4)

par(mfrow = c(3,5))
acf(cur_B[1])
acf(cur_B[2])
acf(cur_B[3])
acf(cur_B[4])
acf(cur_B[5])
ts.plot(cur_B[1], xlab = "iteration", ylab = expression(beta[0]))
ts.plot(cur_B[2], xlab = "iteration", ylab = expression(beta[1]))
ts.plot(cur_B[3], xlab = "iteration", ylab = expression(beta[2]))
ts.plot(cur_B[4], xlab = "iteration", ylab = expression(beta[3]))
ts.plot(cur_B[5], xlab = "iteration", ylab = expression(beta[4]))
hist(unlist(cur_B[1]), main = "", breaks = 30, xlab = expression(beta[0]))
hist(unlist(cur_B[2]), main = "", breaks = 30, xlab = expression(beta[1]))
hist(unlist(cur_B[3]), main = "", breaks = 25, xlab = expression(beta[2]))
hist(unlist(cur_B[4]), main = "", breaks = 25, xlab = expression(beta[3]))
hist(unlist(cur_B[5]), main = "", breaks = 30, xlab = expression(beta[4]))

#mu
cur_mu = data.frame()
for (i in 1:5) {
  for (j in (burn+1):chain_length) {
    cur_mu[j-burn,i] = res$mu[[j]][i]
  }
}
colnames(cur_mu) = paste0("mu", 0:4)

par(mfrow = c(3,5))
acf(cur_mu[1])
acf(cur_mu[2])
acf(cur_mu[3])
acf(cur_mu[4])
acf(cur_mu[5])
ts.plot(cur_mu[1], xlab = "iteration", ylab = expression(mu[0]))
ts.plot(cur_mu[2], xlab = "iteration", ylab = expression(mu[1]))
ts.plot(cur_mu[3], xlab = "iteration", ylab = expression(mu[2]))
ts.plot(cur_mu[4], xlab = "iteration", ylab = expression(mu[3]))
ts.plot(cur_mu[5], xlab = "iteration", ylab = expression(mu[4]))
hist(unlist(cur_mu[1]), main = "", breaks = 30, xlab = expression(mu[0]))
hist(unlist(cur_mu[2]), main = "", breaks = 30, xlab = expression(mu[1]))
hist(unlist(cur_mu[3]), main = "", breaks = 30, xlab = expression(mu[2]))
hist(unlist(cur_mu[4]), main = "", breaks = 30, xlab = expression(mu[3]))
hist(unlist(cur_mu[5]), main = "", breaks = 35, xlab = expression(mu[4]))


#sigmasq
cur_s <- NA
for (i in burn:chain_length) {
  cur_s[i-burn+1] <- res$sigmasq[i]
}

cur_s %>% acf()
cur_s %>% ts.plot()
data.frame(cur_s) %>% ggplot(aes(x = cur_s)) + geom_histogram(bins = 50)

#SIGMA
```

rdata split

```{r}
# res1 <- list(res$B[1:2500], res$mu[1:2500], res$sigmasq[1:2500], res$SIGMA[1:2500])

split_res <- list()
cur_start <- 1
nsplits <- 5
nchain <- chain_length
for (i in 1:nsplits) {
  cur_end <- i*nchain/nsplits
  split_res[[i]] <- list(res$B[cur_start:cur_end], 
                       res$mu[cur_start:cur_end], 
                       res$sigmasq[cur_start:cur_end], 
                       res$SIGMA[cur_start:cur_end])
  cur_start <- cur_start + (nchain/nsplits)
}

res1 <- split_res[[1]]
res2 <- split_res[[2]]
res3 <- split_res[[3]]
res4 <- split_res[[4]]
res5 <- split_res[[5]]

save(res1, file = "generated_data/mcmc_split1.RData")
save(res2, file = "generated_data/mcmc_split2.RData")
save(res3, file = "generated_data/mcmc_split3.RData")
save(res4, file = "generated_data/mcmc_split4.RData")
save(res5, file = "generated_data/mcmc_split5.RData")

```



