---
title: "probelm5"
author: "Paulina Han, Yida Wang"
date: '2022-05-05'
output: pdf_document
---

```{r}
load("generated_data/B_final.Rdata")
source("shared_code/data_cleaning.R")
library(tidyverse)
library(ggplot2)
##lm model:
working_dt <- dt_for5

#regress on beta_0:
y0 = B_final[ 1:678 , 1]
month = 
  working_dt %>% 
  dplyr::select(id, month) %>% 
  pull(month)
year = 
  working_dt %>% 
  dplyr::select(id, year) %>% 
  pull(year)
type = 
  working_dt %>% 
  dplyr::select(id, type) %>% 
  pull(type)

season = 
  working_dt %>% 
  dplyr::select(id, season) %>% 
  pull(season)

# lm_b0_year = lm(y0 ~ month + year + type)
# lm_b0_season = lm(y0 ~ season + year + type)
# summary(lm_b0_year)
# summary(lm_b0_season)
```

# Do some EDA before fiting models
```{r}
B_final1 = B_final %>% as.data.frame()
names(B_final1)[1] <- "beta0"
names(B_final1)[2] <- "beta1"
names(B_final1)[3] <- "beta2"
names(B_final1)[4] <- "beta3"
names(B_final1)[5] <- "beta4"
head(B_final1)
ts1 = data.frame(B_final1, season)

ts1_df = ts1 %>% 
  pivot_longer(
    c(beta0:beta4),
    names_to = "beta",
    values_to = "beta_vals"
  ) 

ggplot(data = ts1_df, aes(x = season, y = beta_vals, color = beta)) + geom_point() + geom_boxplot() 
#+ facet_grid(season~beta, scale = "free_y")
```

```{r}
ts2 = data.frame(B_final1, year)
head(ts2)

ts2_df = ts2 %>% 
  pivot_longer(
    c(beta0:beta4),
    names_to = "beta",
    values_to = "beta_vals"
  ) 

ggplot(data = ts2_df, aes(x = year, y = beta_vals, color = beta)) + geom_point()
```

## B0

```{r}
#regress on beta_0:
y0 = B_final[1: 678 ,1]
lm_b0 = lm(y0 ~ factor(month) + year + factor(type))
lm_b0_season = lm(y0~ factor(season) + year + factor(type))
summary(lm_b0)
summary(lm_b0_season)

```

## B1

```{r}
#regress on beta_1:
y1 = B_final[1: 678,2]
lm_b1 = lm(y1 ~ factor(month) + year + factor(type))
lm_b1_season = lm(y1~ factor(season) + year + factor(type))
summary(lm_b1)
summary(lm_b1_season)

```

## B2

```{r}
#regress on beta_2:
y2 = B_final[1: 678,3]
lm_b2 = lm(y2 ~ factor(month) + year + factor(type))
lm_b2_season = lm(y2~ factor(season) + year + factor(type))
summary(lm_b2)
summary(lm_b2_season)

```


## B3

```{r}
#regress on beta_3:
y3 = B_final[1: 678,4]
lm_b3 = lm(y3 ~ factor(month) + year + factor(type))
lm_b3_season = lm(y3~ factor(season) + year + factor(type))
summary(lm_b3)
summary(lm_b3_season)

```

## B4

```{r}
#regress on beta_4:
y4 = B_final[1: 678,5]
lm_b4 = lm(y4 ~ factor(month) + year + factor(type))
lm_b4_season = lm(y4~ factor(season) + year + factor(type))
summary(lm_b4)
summary(lm_b4_season)
```

Tables for coefficients
```{r}
b0 = summary(lm_b0)$coefficients %>% as.data.frame %>% rownames_to_column() %>% select(rowname, Estimate) %>%
  rename(b0 = Estimate)
b1 = summary(lm_b1)$coefficients %>% as.data.frame %>% rownames_to_column() %>% select(rowname, Estimate) %>%
  rename(b1 = Estimate)
b2 = summary(lm_b2)$coefficients %>% as.data.frame %>% rownames_to_column() %>% select(rowname, Estimate) %>%
  rename(b2 = Estimate)
b3 = summary(lm_b3)$coefficients %>% as.data.frame %>% rownames_to_column() %>% select(rowname, Estimate) %>%
  rename(b3 = Estimate)
b4 = summary(lm_b4)$coefficients %>% as.data.frame %>% rownames_to_column() %>% select(rowname, Estimate) %>%
  rename(b4 = Estimate)
table_lm = list(b0,b1,b2,b3,b4) %>% reduce(full_join, by = "rowname")

b0_sea = summary(lm_b0_season)$coefficients %>% as.data.frame %>% rownames_to_column() %>% select(rowname, Estimate) %>%
  rename(b0 = Estimate)
b1_sea = summary(lm_b1_season)$coefficients %>% as.data.frame %>% rownames_to_column() %>% select(rowname, Estimate) %>%
  rename(b1 = Estimate)
b2_sea = summary(lm_b2_season)$coefficients %>% as.data.frame %>% rownames_to_column() %>% select(rowname, Estimate) %>%
  rename(b2 = Estimate)
b3_sea = summary(lm_b3_season)$coefficients %>% as.data.frame %>% rownames_to_column() %>% select(rowname, Estimate) %>%
  rename(b3 = Estimate)
b4_sea = summary(lm_b4_season)$coefficients %>% as.data.frame %>% rownames_to_column() %>% select(rowname, Estimate) %>%
  rename(b4 = Estimate)
table_sealm = list(b0_sea,b1_sea,b2_sea,b3_sea,b4_sea) %>% reduce(full_join, by = "rowname")

table_lm %>% knitr::kable()
table_sealm %>% knitr::kable()
```



