---
title: "Problem 6"
author: "Lin Yang"
date: "5/9/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(glmnet)
library(caret)
library(MASS)
```


```{r}
load("generated_data/B_final.RData")
source("shared_code/data_cleaning.R")
id <- train$id %>% unique()
B_final %>% dim()

B_reg <- tibble(
  id = id,
  b0 = B_final[,1], 
  b1 = B_final[,2],
  b2 = B_final[,3],
  b3 = B_final[,4],
  b4 = B_final[,5]
)
B_reg <- B_reg %>% mutate(id = tolower(id))

dat6 <- read.csv("data/hurricanoutcome2.csv") %>% 
  janitor::clean_names() %>% 
  mutate(damage = as.numeric(str_replace(damage, "\\$", "")),
         deaths = as.integer(gsub(",", "", deaths)),
         month = as.factor(month),
         nature = as.factor(nature)) %>% 
  rename(id = hurrican_id)

dat6new <- left_join(dat6, B_reg, by = "id") %>% dplyr::select(-1)
```


```{r}
#damage
damage_x <- model.matrix(damage ~ ., dat6new)[ ,-1]
damage_y <- dat6new$damage

set.seed(1)
ctrl <- trainControl(method = "repeatedcv")
damage.fit <- train(damage_x, damage_y,
                   method = "glmnet",
                   preProcess = "scale",
                   tuneGrid = expand.grid(alpha = 1, 
                                          lambda = exp(seq(5, -3, length = 100))),
                   trControl = ctrl)

damage.fit$bestTune
coef(damage.fit$finalModel, damage.fit$bestTune$lambda) %>% 
  as.matrix() %>% 
  knitr::kable(col.names = gsub("[.]", " ", "Coefficients"))

#refit a linear regression model
damage.lm <- lm(damage ~ season + maxspeed + total_pop + percent_usa + b2, data = dat6new)
summary(damage.lm)

fit <- lm(damage ~., data = dat6)
summary(fit)
```


```{r}
#deaths
#quantile(dat6$deaths, 0.95)
#dat_death <- dat6 %>% filter(deaths <= 1000)
#boxplot(dat6$deaths)
#summary(dat_death)
death_x <- model.matrix(deaths ~ ., dat6new)[ ,-1]
death_y <- dat6new$deaths

set.seed(100)
death.fit <- train(deaths ~ season+damage+deaths+month+nature+maxspeed+meanspeed+maxpressure+meanpressure+total_pop+percent_poor+percent_usa+b0+b1+b2+b3+b4+ offset(hours),
                   data = dat6new,
                   method = "glmnet",
                   family = "poisson",
                   preProcess = "scale",
                   tuneGrid = expand.grid(alpha = 1, 
                                          lambda = exp(seq(-4, 5, length = 500))),
                   trControl = ctrl)
plot(death.fit)
death.fit$bestTune
coef(death.fit$finalModel, death.fit$bestTune$lambda) %>% 
  as.matrix() %>% 
  knitr::kable(col.names = gsub("[.]", " ", "Coefficients"))


poi_fit = glm(deaths ~ season+damage+deaths+month+nature+maxspeed+meanspeed+maxpressure+meanpressure+total_pop+percent_poor+percent_usa+b0+b1+b2+b3+b4+offset(log(hours)), family = poisson(link=log), data = dat6)
summary(poi_fit)

#wave.nb=glm.nb(deaths ~season+damage+deaths+month+nature+maxspeed+meanspeed+maxpressure+mea#npressure+total_pop+percent_poor+percent_usa+ offset(log(hours)), data = dat6)
#summary(wave.nb)
#sqrt(sum((predict(wave.nb, newdata = dat6) - dat6$deaths)^2))



#sqrt(sum((predict(poi_fit, newdata = dat6) - dat6$deaths)^2))
#summary(dat6$deaths)
```





